name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# Global build optimizations to save RAM
env:
  # Use lld linker and reduce debug info to the absolute minimum
  RUSTFLAGS: "-C link-arg=-fuse-ld=lld -C debuginfo=0"
  # Tell cargo to use less concurrency to save RAM
  CARGO_BUILD_JOBS: 2

jobs:
  build-and-release:
    runs-on: codeberg-medium
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust Toolchain
        uses: https://codeberg.org/wackbyte/rust-toolchain@trunk
        with:
          toolchain: stable
          targets: x86_64-pc-windows-gnu

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev mingw-w64 lld

      - name: Install cargo-deb (from .deb)
        run: |
          wget https://github.com/kornelski/cargo-deb/releases/download/v3.6.2/cargo-deb_3.6.2-1_amd64.deb
          sudo dpkg -i cargo-deb_3.6.2-1_amd64.deb

      # --- BUILD LINUX ---
      - name: Build Linux (Release)
        run: cargo build --release --features gui

      - name: Create Linux Packages
        run: |
          # The command remains the same as dpkg puts it in the PATH
          cargo deb --no-build --features gui 
          
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="debug-${{ github.sha }}"
          fi
          
          STAGING="cfait-$VERSION"
          mkdir -p "$STAGING"
          cp target/release/cfait "$STAGING/"
          cp target/release/gui "$STAGING/cfait-gui"
          cp README.md LICENSE "$STAGING/"
          cp assets/cfait.desktop "$STAGING/"
          cp assets/cfait.svg "$STAGING/"
          tar -czvf "cfait-linux-$VERSION.tar.gz" "$STAGING"

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            SOURCE_URL="${{ github.server_url }}/${{ github.repository }}/archive/${{ github.ref_name }}.tar.gz"
            curl -L -O "$SOURCE_URL"
            HASH=$(sha256sum "${{ github.ref_name }}.tar.gz" | awk '{print $1}')
            sed -i "s/'SKIP'/'$HASH'/" packaging/arch/PKGBUILD
            cp packaging/arch/PKGBUILD PKGBUILD-release
          fi

      # --- BUILD WINDOWS (CROSS) ---
      - name: Build Windows (Cross-compile)
        env:
          RUSTFLAGS: "" # Reset flags for Windows build
        run: |
          cargo build --release --target x86_64-pc-windows-gnu --features gui

      - name: Package Windows
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="debug-${{ github.sha }}"
          fi

          mkdir -p windows-staging
          cp target/x86_64-pc-windows-gnu/release/cfait.exe windows-staging/
          cp target/x86_64-pc-windows-gnu/release/gui.exe windows-staging/cfait-gui.exe
          cp README.md LICENSE windows-staging/
          
          cd windows-staging
          zip -r "../cfait-windows-$VERSION.zip" .
          cd ..

      # --- UPLOAD SECTION ---
      - name: Install Tea (Gitea CLI)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          wget -O tea https://dl.gitea.io/tea/0.9.2/tea-0.9.2-linux-amd64
          chmod +x tea
          sudo mv tea /usr/local/bin/

      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          wget https://github.com/orhun/git-cliff/releases/download/v2.10.1/git-cliff-2.10.1-x86_64-unknown-linux-gnu.tar.gz -O git-cliff.tar.gz
          tar -xzf git-cliff.tar.gz
          sudo mv git-cliff-2.10.1/git-cliff /usr/local/bin/
          git-cliff --config cliff.toml --verbose --latest --strip header --output CHANGELOG_RELEASE.md

      - name: Create Release and Upload
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TEA_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          tea login add --name codeberg --url ${{ github.server_url }} --token ${{ secrets.RELEASE_TOKEN }}
          
          tea release create --repo ${{ github.repository }} --tag ${{ github.ref_name }} --title ${{ github.ref_name }} --note-file CHANGELOG_RELEASE.md

          tea release upload --repo ${{ github.repository }} --tag ${{ github.ref_name }} --file target/debian/*.deb
          tea release upload --repo ${{ github.repository }} --tag ${{ github.ref_name }} --file cfait-linux-*.tar.gz
          tea release upload --repo ${{ github.repository }} --tag ${{ github.ref_name }} --file cfait-windows-*.zip
          tea release upload --repo ${{ github.repository }} --tag ${{ github.ref_name }} --file PKGBU_