name: Test and Lint

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted-rust
    
    container:
      image: ghcr.io/catthehacker/ubuntu:rust-latest
      volumes:
        - cargo-registry:/usr/local/cargo/registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev

      - name: Run linter (clippy)
        run: cargo clippy --all-features -- -D warnings

      - name: Run unit tests
        run: cargo test --all-features --verbose